version: '3.8'

services:
  mysql:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: despacho_db
      MYSQL_USER: ${MYSQL_USER:-despacho_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-despacho_pass}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - proyecto-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always

  # 2. MICROSERVICIO DE DESPACHOS
  backend-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      dockerfile: Dockerfile
    container_name: backend_despachos
    ports:
      - "8080:8081" # Mapea tu puerto local 8080 al 8081 interno de Spring Boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/despacho_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-despacho_user}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-despacho_pass}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - proyecto-network

  # 3. FRONTEND (Nginx)
  frontend:
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
    container_name: front_despachos
    ports:
      - "80:80"
    depends_on:
      - backend-despachos # <-- Ahora solo depende de despachos
    networks:
      - proyecto-network
    restart: always

volumes:
  mysql_data:

networks:
  proyecto-network:
    driver: bridge