name: CI/CD Proyecto Semestral - Backend

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      id: login-ecr

    - name: Build imagen Backend y push a ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: backend_despachos
        IMAGE_TAG: latest
      run: |
        cd back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Desplegar Backend mediante AWS SSM
      run: |
        aws ssm send-command \
          --instance-ids *** \
          --document-name "AWS-RunShellScript" \
          --comment "Desplegar Backend con credenciales" \
          --parameters '{
            "commands":[
              "set -e",
              "aws ecr get-login-password --region *** | sudo docker login --username AWS --password-stdin ***",
              "sudo docker pull ***/backend_despachos:latest",
              "sudo docker stop backend_despachos || true",
              "sudo docker rm backend_despachos || true",
              "sudo docker run -d --name backend_despachos -p 8080:8080 -e SPRING_DATASOURCE_URL=\"jdbc:mysql://***:3306/despacho_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true\" -e SPRING_DATASOURCE_USERNAME=\"***\" -e SPRING_DATASOURCE_PASSWORD=\"***\" ***/backend_despachos:latest"
            ]
          }' \
          --output text