name: CI/CD Proyecto Semestral - Backend

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      id: login-ecr

    - name: Build imagen Backend y push a ECR
      env:
        ECR_REGISTRY: 206916371090.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: backend_despachos
        IMAGE_TAG: latest
      run: |
        cd back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Desplegar Backend vía SSM
      run: |
        aws ssm send-command \
        --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} \
        --document-name "AWS-RunShellScript" \
        --comment "Actualizar backend_despachos desde ECR" \
        --parameters '{"commands":[
          "set -e",
          "export AWS_REGION=${{ secrets.AWS_REGION }}",
          "aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 206916371090.dkr.ecr.us-east-1.amazonaws.com",
          "docker pull 206916371090.dkr.ecr.us-east-1.amazonaws.com/backend_despachos:latest",
          "docker stop backend_despachos || true",
          "docker rm backend_despachos || true",
          "docker run -d --name backend_despachos -p 8080:8080 -e DB_HOST=${{ secrets.DATABASE_EC2_IP }} -e DB_PORT=3306 -e DB_NAME=despacho_db -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }} 206916371090.dkr.ecr.us-east-1.amazonaws.com/backend_despachos:latest"
        ]}' \
        --output text