name: CI/CD Proyecto Semestral - Database

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-push-deploy-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      id: login-ecr

    - name: Build imagen Database y push a ECR
      env:
        ECR_REGISTRY: 206916371090.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: db
        IMAGE_TAG: latest
      run: |
        cd db
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Desplegar Database vía SSM
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_DATABASE_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Actualizar db desde ECR" \
          --parameters '{"commands":[
            "set -e",
            "export AWS_REGION=${{ secrets.AWS_REGION }}",
            "aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 206916371090.dkr.ecr.us-east-1.amazonaws.com",
            "docker pull 206916371090.dkr.ecr.us-east-1.amazonaws.com/db:latest",
            "docker stop db || true",
            "docker rm db || true",
            "docker run -d --name db -p 3306:3306 -v mysql_data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} -e MYSQL_DATABASE=despacho_db -e MYSQL_USER=${{ secrets.DB_USER }} -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} 206916371090.dkr.ecr.us-east-1.amazonaws.com/db:latest"
          ]}' \
          --output text